"""Renders data/synthetic/README.md -- generated fresh each run so it always
describes the actual defect set produced, not a stale hand-written summary.
"""

from __future__ import annotations

from .config import SimConfig

_DEFECT_TYPE_LABELS = {
    "split": "Field split",
    "merge": "Field merge",
    "rename": "Field renamed",
    "rental_lost": "Rental ground lost",
    "naming_drift": "Naming drift",
    "yield_monitor_calibration_error": "Yield monitor calibration error",
    "missing_swath": "Missing swath (GPS dropout)",
    "no_yield_monitor": "No monitor at all",
    "spreadsheet_merged_header": "Spreadsheet mess: merged header cells",
    "spreadsheet_notes_column": "Spreadsheet mess: notes column",
    "spreadsheet_totals_row_in_range": "Spreadsheet mess: totals row inside data range",
    "spreadsheet_blank_rows": "Spreadsheet mess: blank rows",
    "cost_basis_total_dollars": "Spreadsheet mess: total-dollars cost basis",
    "transposed_digit": "Spreadsheet mess: transposed digit",
    "unit_inconsistency": "Unit inconsistency (N rate)",
    "weather_shortfall": "Weather shortfall (forced drought)",
    "management_shortfall": "Management shortfall (yield override)",
}


def render_readme(config: SimConfig, ground_truth: dict) -> str:
    defects = ground_truth["defects"]
    seasons = config.seasons

    by_type: dict[str, list[dict]] = {}
    for d in defects:
        by_type.setdefault(d["type"], []).append(d)

    lines = [
        "# Precision Farm MCP -- Synthetic Data",
        "",
        "**All data in this directory is synthetic.** It was generated by "
        "`generator/` for one fictional North Dakota corn/soybean operation and "
        "is not derived from any real farm, field, or grower.",
        "",
        f"- Seed: `{config.random_seed}`",
        f"- Root fields: {config.num_fields}",
        f"- Seasons: {seasons[0]}-{seasons[-1]} ({len(seasons)} seasons)",
        f"- Generator version: {ground_truth['generator']['version']}",
        "",
        "Regenerate identically with:",
        "",
        "```bash",
        f"uv run python -m farm_data_gen.cli --seed {config.random_seed} "
        f"--fields {config.num_fields} --seasons {config.num_seasons} --out data/synthetic",
        "```",
        "",
        "## Outputs",
        "",
        "| Directory / file | Format | Notes |",
        "|---|---|---|",
        "| `boundaries/` | GeoJSON, one file per season | CRS varies by season -- see "
        "`ground_truth.json` `identity_events` / per-season files for which |",
        "| `yield_monitor/` | CSV, one file per field per season | Absent for the two "
        "oldest seasons (older combine) |",
        "| `scale_tickets/` | CSV, one file per season | Authoritative bushel source |",
        "| `as_applied/` | CSV, one file per season | Newest 4 seasons only |",
        "| `cost_ledger.xlsx` | XLSX workbook | One tab per season plus a shared "
        "`Unit Prices` tab; this is the farmer's own messy spreadsheet |",
        "| `ground_truth.json` | JSON | Exact expected profit per field per season, "
        "every injected defect with a stable ID, and the field-identity event graph |",
        "",
        "## Why each defect exists",
        "",
        "Every defect below is deliberate and recorded in `ground_truth.json` under "
        "`defects[]` with a stable `defect_id`, so a downstream test suite can assert "
        "each one was actually detected and handled -- a generator that only produced "
        "clean data would let a broken profitability engine pass its tests for free.",
        "",
    ]

    for defect_type, records in sorted(by_type.items(), key=lambda kv: kv[0]):
        label = _DEFECT_TYPE_LABELS.get(defect_type, defect_type)
        lines.append(f"### {label}")
        lines.append("")
        for r in records[:5]:
            season_note = f" (season {r['season']})" if r.get("season") else ""
            lines.append(f"- `{r['defect_id']}`{season_note}: {r['detail']}")
        if len(records) > 5:
            lines.append(f"- ...and {len(records) - 5} more of this type.")
        lines.append("")

    lines += [
        "## Field identity",
        "",
        "The farmer's field name is never a stable key across all ten seasons -- it "
        "drifts, gets formally renamed, and stops meaning anything across a split or "
        "merge. `ground_truth.json`'s `canonical_fields` and `identity_events` are the "
        "answer key for resolving this; the raw files (GeoJSON/CSV/XLSX) intentionally "
        "carry only the farmer-visible name as of that season, drift included, never "
        "an internal canonical ID.",
        "",
        "## Limitations",
        "",
        "- EPSG:26914 coordinates are produced by a lightweight planar approximation, "
        "not a full geodetic Transverse Mercator projection -- plausible magnitude and "
        "a correctly declared CRS, not survey-grade accuracy.",
        "- Field boundaries are simple axis-aligned rectangles sized to match assigned "
        "acreage, not real parcel geometry.",
        "",
    ]

    return "\n".join(lines) + "\n"
